version: '1.0'

services:
  propiedades-db:
    container_name: 'propiedades-db'
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    restart: always

  propiedades:
    container_name: 'propiedades'
    build:
      context: ./src/propiedades
      dockerfile: Dockerfile
    working_dir: /app/
    env_file:
      - .env
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres_data:
