version: '1.0'
networks:
  catastral:

services:
  propiedades-db:
    container_name: 'propiedades-db'
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - catastral
    restart: always

  propiedades:
    container_name: 'propiedades'
    build:
      context: .
      dockerfile: propiedades.Dockerfile
    working_dir: /app/
    env_file:
      - .env
    depends_on:
      - propiedades-db
    ports:
      - 3000:3000
    networks:
      - catastral
    restart: always

volumes:
  postgres_data:
