version: "1.0"
networks:
  catastral:
  geoespacial:
  propiedad:
  contrato:
  pulsar:
    driver: bridge

volumes:
  pg_catastral_data:
  pg_geoespacial_data:
  pg_contratos_data:
  pg_propiedades_data:

services:
  broker-standalone:
    image: apachepulsar/pulsar:3.2.0
    container_name: broker-standalone
    profiles: ["pulsar", "full"]
    restart: on-failure
    networks:
      - pulsar
    ports:
      - "6650:6650"
      - "8080:8080"
    command: ["bin/pulsar", "standalone"]

  catastrales-db:
    container_name: "catastrales-db"
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - pg_catastral_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - catastral
    restart: always
  
  geoespaciales-db:
    container_name: "geoespaciales-db"
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - pg_geoespacial_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - geoespacial
    restart: always
  
  contratos-db:
    container_name: "contratos-db"
    image: postgres
    env_file:
      - .env.contratos
    environment:
      PGDATA: /data/postgres
    volumes:
      - pg_contratos_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    networks:
      - contrato
    restart: always
  
  propiedades-db:
    container_name: "propiedades-db"
    image: postgres
    env_file:
      - .env
    environment:
      PGDATA: /data/postgres
    volumes:
      - pg_propiedades_data:/var/lib/postgresql/data/
    ports:
      - 5433:5432
    networks:
      - propiedad
    restart: always

  catastrales-api:
    container_name: "catastrales-api"
    build:
      context: .
      dockerfile: catastrales.Dockerfile
    environment:
      - DB_HOST=catastrales-db
    env_file:
      - .env
    depends_on:
      - catastrales-db
    ports:
      - 3000:3000
    networks:
      - catastral
      - pulsar
    restart: always

  geoespaciales-api:
    container_name: "geoespaciales-api"
    build:
      context: .
      dockerfile: geoespaciales.Dockerfile
    environment:
      - DB_HOST=geoespaciales-db
    env_file:
      - .env
    depends_on:
      - geoespaciales-db
    ports:
      - 3003:3003
    networks:
      - geoespacial
      - pulsar
    restart: always
  
  contratos-api:
    container_name: "contratos-api"
    build:
      context: .
      dockerfile: contratos.Dockerfile
    environment:
      - DB_HOST=contratos-db
    env_file:
      - .env.contratos
    depends_on:
      - contratos-db
    ports:
      - 3002:3002
    networks:
      - contrato
      - pulsar
    restart: always

  propiedades-api:
    container_name: "propiedades-api"
    build:
      context: .
      dockerfile: propiedades.Dockerfile
    environment:
      - DB_HOST=propiedades-db
    env_file:
      - .env
    depends_on:
      - propiedades-db
    ports:
      - 3001:3001
    networks:
      - propiedad
      - pulsar
    restart: always